[workspace]
members = [
    "services",
    "dash",
    "cli",
]

[workspace.metadata.release]
verify = true

[package]
name = "printnanny"
version = "0.10.4"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
printnanny-cli = { path = "cli" }
printnanny-dash = { path = "dash" }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
