[package]
name = "printnanny"
version = "0.1.1"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
anyhow = "1.0"
clap = "2.33"
dirs = "4.0.0"
log = "0.4"
simple_logger = "1.13"