[workspace]
members = [
    "cli",
    "dbus",
    "services",
    "nats",
]
[build]
targets = [
    "aarch64-unknown-linux-gnu",
    "armv7-unknown-linux-gnueabihf",
    "x86_64-unknown-linux-gnu",
]
