[package]
name = "printnanny"
version = "0.1.1"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
anyhow = "1.0.44"
clap = "2.33.3"
config = "0.11.0"
dialoguer = "0.8.0"
dirs = "4.0.0"
env_logger = "0.9.0"
glob = "0.3.0"
log = "0.4.14"
print-nanny-client = "0.8.26"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
thiserror = "1.0.29"
term_size = "0.3.2"
tokio = { version = "1.12.0", features = ["full"] }