[package]
name = "printnanny"
version = "0.1.1"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
clap = "2.33.3"
anyhow = "1.0.44"
confy = "0.4.0"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4.14"
print-nanny-client = "0.8.6-dev3"