[package]
name = "printnanny"
version = "0.1.3"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = "2.33.3"
config = "0.11.0"
console = "0.14.1"
dialoguer = "0.8.0"
dirs = "4.0.0"
env_logger = "0.9.0"
glob = "0.3.0"
http = "0.2.5"
log = "0.4.14"
print-nanny-client = "0.8.47"
procfs = "0.11.0"
rumqttc = "0.9.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sha2 = "0.9.8"
sys-info = "0.9"
thiserror = "1.0.29"
term_size = "0.3.2"
tokio = { version = "1.12.0", features = ["full"] }
openssl = { version = "=0.10.36", features = ["vendored"] }

[dev-dependencies]
assert_cmd = "2.0.2"
mockall = "0.10.2"
predicates = "2.0.3"
tempdir = "0.3.7"