[workspace]
members = [
    "services",
    "dash",
    "cli",
]
[package]
name = "printnanny"
version = "0.9.4"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

[dependencies]
printnanny-cli = { path = "cli"}
printnanny-dash = { path = "dash" }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
