[workspace]
members = [
    "services",
    "dash",
    "cli",
]

[workspace.metadata.release]
verify = true
tag = false

[package]
name = "printnanny"
version = "0.19.0"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2021"
rust-version = "1.59"
license = "AGPL-3.0-or-later"
description = "PrintNanny root package crate"
[dependencies]
printnanny-cli = { path = "cli", version = "^0.19.0"}
printnanny-dash = { path = "dash", version = "^0.19.0"}
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
