[target.aarch64-unknown-linux-gnu]
image = "bitsyai/cross:aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "bitsyai/cross:armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-linux-gnueabihf]
image = "bitsyai/cross:x86_64-unknown-linux-gnu"