[target.aarch64-unknown-linux-gnu]
image = "bitsyai/cross:aarch64-unknown-linux-gnu-0.2.1"

[target.armv7-unknown-linux-gnueabihf]
image = "bitsyai/cross:armv7-unknown-linux-gnueabihf-0.2.1"

[target.x86_64-unknown-linux-gnueabihf]
image = "bitsyai/cross:x86_64-unknown-linux-gnu-0.2.1"