[package]
name = "printnanny-cli"
description = "Print Nanny Command-line Interface"
license = "AGPL-3.0-or-later"
version = "0.10.7"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

[dependencies]
printnanny-services = {path = "../services", version = "0.10.3"}
printnanny-api-client = "0.42.1"
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = "2.3.7"
env_logger = "0.9"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4"

[dependencies.function_name]
version = "0.2.0"
