[package]
name = "printnanny-cli"
description = "PrintNanny Command-line Interface"
license = "AGPL-3.0-or-later"
version = "0.22.4"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2021"
rust-version = "1.59"
repository = "https://github.com/bitsy-ai/printnanny-cli.git"

[dependencies]
printnanny-dash = {path = "../dash", version = "^0.22.0-rc.5"}
printnanny-services = {path = "../services", version = "^0.22.0-rc.5"}
printnanny-api-client = "0.83.0"
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = { version = "3", features = ["derive", "cargo", "env", "wrap_help"] }
env_logger = "0.9"
git-version = "0.3.5"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4"
serde_json = "1" 
toml = "0.5.9"
serde = "1.0.137"

[dependencies.function_name]
version = "0.2.0"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json","secrets", "tls"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["handlebars", "tera"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.2"
default-features = false
features = ["diesel_sqlite_pool"]
