[package]
name = "printnanny-cli"
description = "Print Nanny Command-line Interface"
license = "GNU Affero General Public License version 3"
version = "0.10.2"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

[dependencies]
printnanny-services = {path = "../services", version = "*"}
printnanny-api-client = "0.39.4"
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = "2.3.7"
env_logger = "0.9"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4"

[dependencies.function_name]
version = "0.2.0"
