[package]
name = "printnanny-cli"
description = "Print Nanny Command-line Interface"
license = "AGPL-3.0-or-later"
version = "0.18.0"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2021"
rust-version = "1.59"

[dependencies]
printnanny-services = {path = "../services", version = "^0.18.0"}
printnanny-api-client = "0.65.1"
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = { version = "3", features = ["derive", "cargo", "env", "wrap_help"] }
env_logger = "0.9"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4"
serde_json = "1" 

[dependencies.function_name]
version = "0.2.0"
