[package]
name = "printnanny"
version = "0.9.4"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

[dependencies]
services = {path = "../services"}
printnanny-api-client = "0.37"
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = "2.3.7"
env_logger = "0.9"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4"

[dependencies.function_name]
version = "0.2.0"