# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
import_types = ["diesel::sql_types::*", "crate::sql_types::*"]   # <- note the extra imports for diesel-derive-enum


[migrations_directory]
dir = "migrations"
