[package]
name = "printnanny-dash"
version = "0.1.0"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

[dependencies]
services = {path = "../services"}
log = "0.4" 
anyhow = "1"
rocket = "0.5.0-rc.1"
time = { version = "0.3", features = ["macros", "parsing"] }
tokio = "1.15.0"

[dependencies.clap]
version = "3.0"
features = ["cargo"]

[dependencies.rocket_auth]
version = "0.4.0"
features = ["sqlx-sqlite"]

[dependencies.sqlx]
version = "0.5"
features = [ "runtime-tokio-rustls" ]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["handlebars", "tera"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
default-features = false
features = ["diesel_sqlite_pool"]